upstream:
  service:
    name: traefik-websecure-internal
    port: 8444

dns:
  hostAdmin: "SET_BY_ARGOCD"
  pathRule: "PathPrefix(`/`)"
  certificate:
    name: admin
    clusterIssuer: letsencrypt
